"""make_order_user_id_nullable

Revision ID: 1816f5262a74
Revises: f7632cc008ee
Create Date: 2026-02-17 14:33:31.549062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1816f5262a74'
down_revision: Union[str, None] = 'f7632cc008ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btc_market_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_start', sa.String(length=32), nullable=False),
    sa.Column('round_end', sa.String(length=32), nullable=False),
    sa.Column('btc_price_at_open', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('btc_price_at_close', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'FAILED', name='btcroundstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_btc_market_rounds_round_start'), 'btc_market_rounds', ['round_start'], unique=True)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.String(length=66), nullable=False),
    sa.Column('question_id', sa.String(length=66), nullable=False),
    sa.Column('oracle_address', sa.String(length=42), nullable=False),
    sa.Column('collateral_token', sa.String(length=42), nullable=False),
    sa.Column('yes_token_id', sa.String(length=80), nullable=True),
    sa.Column('no_token_id', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('resolution_time', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'CANCELLED', name='marketstatus'), nullable=False),
    sa.Column('yes_payout', sa.Integer(), nullable=True),
    sa.Column('no_payout', sa.Integer(), nullable=True),
    sa.Column('yes_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('no_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('volume_24h', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('total_volume', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('btc_round_id', sa.Integer(), nullable=True),
    sa.Column('strike_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('strike_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['btc_round_id'], ['btc_market_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_btc_round_id'), 'markets', ['btc_round_id'], unique=False)
    op.create_index(op.f('ix_markets_condition_id'), 'markets', ['condition_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('condition_id', sa.String(length=66), nullable=False),
    sa.Column('token_id', sa.String(length=80), nullable=False),
    sa.Column('maker_address', sa.String(length=42), nullable=False),
    sa.Column('maker_amount', sa.String(length=40), nullable=False),
    sa.Column('taker_amount', sa.String(length=40), nullable=False),
    sa.Column('expiration', sa.BigInteger(), nullable=False),
    sa.Column('nonce', sa.BigInteger(), nullable=False),
    sa.Column('fee_rate_bps', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('signer', sa.String(length=42), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('order_hash', sa.String(length=66), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIAL', 'FILLED', 'CANCELLED', 'EXPIRED', name='orderstatus'), nullable=False),
    sa.Column('filled_amount', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_condition_id'), 'orders', ['condition_id'], unique=False)
    op.create_index(op.f('ix_orders_maker_address'), 'orders', ['maker_address'], unique=False)
    op.create_index(op.f('ix_orders_order_hash'), 'orders', ['order_hash'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_token_id'), 'orders', ['token_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maker_order_id', sa.Integer(), nullable=False),
    sa.Column('taker_order_id', sa.Integer(), nullable=True),
    sa.Column('maker_address', sa.String(length=42), nullable=False),
    sa.Column('taker_address', sa.String(length=42), nullable=False),
    sa.Column('token_amount', sa.String(length=40), nullable=False),
    sa.Column('collateral_amount', sa.String(length=40), nullable=False),
    sa.Column('fee', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SETTLED', 'FAILED', name='fillstatus'), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('settled_at', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['maker_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['taker_order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_maker_order_id'), 'fills', ['maker_order_id'], unique=False)
    op.create_index(op.f('ix_fills_taker_order_id'), 'fills', ['taker_order_id'], unique=False)
    op.drop_index('ix_signing_proxies_user_id', table_name='signing_proxies')
    op.drop_table('signing_proxies')
    op.drop_index('ix_trading_instances_user_id', table_name='trading_instances')
    op.drop_table('trading_instances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_instances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('script', postgresql.ENUM('KEYS1', 'KEYS2', 'AUTO1', 'AUTO2', name='scripttype'), autoincrement=False, nullable=False),
    sa.Column('markets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'PAUSED', 'STOPPED', 'ERROR', 'DEAD', name='instancestatus'), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('pnl', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('celery_task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('orderbook_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('current_increment', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='trading_instances_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trading_instances_pkey')
    )
    op.create_index('ix_trading_instances_user_id', 'trading_instances', ['user_id'], unique=False)
    op.create_table('signing_proxies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kalshi_api_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('encrypted_private_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='signing_proxies_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='signing_proxies_pkey'),
    sa.UniqueConstraint('user_id', name='signing_proxies_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_signing_proxies_user_id', 'signing_proxies', ['user_id'], unique=False)
    op.drop_index(op.f('ix_fills_taker_order_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_maker_order_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_token_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_hash'), table_name='orders')
    op.drop_index(op.f('ix_orders_maker_address'), table_name='orders')
    op.drop_index(op.f('ix_orders_condition_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_markets_condition_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_btc_round_id'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_btc_market_rounds_round_start'), table_name='btc_market_rounds')
    op.drop_table('btc_market_rounds')
    # ### end Alembic commands ###
